// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: services/synapse/message.proto

package synapse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonrpc string          `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Method  string          `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params  *structpb.Value `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	// Types that are assignable to Id:
	//
	//	*JsonRpcRequest_StringId
	//	*JsonRpcRequest_NumberId
	Id isJsonRpcRequest_Id `protobuf_oneof:"id"`
}

func (x *JsonRpcRequest) Reset() {
	*x = JsonRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_synapse_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRpcRequest) ProtoMessage() {}

func (x *JsonRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_synapse_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRpcRequest.ProtoReflect.Descriptor instead.
func (*JsonRpcRequest) Descriptor() ([]byte, []int) {
	return file_services_synapse_message_proto_rawDescGZIP(), []int{0}
}

func (x *JsonRpcRequest) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *JsonRpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *JsonRpcRequest) GetParams() *structpb.Value {
	if x != nil {
		return x.Params
	}
	return nil
}

func (m *JsonRpcRequest) GetId() isJsonRpcRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *JsonRpcRequest) GetStringId() string {
	if x, ok := x.GetId().(*JsonRpcRequest_StringId); ok {
		return x.StringId
	}
	return ""
}

func (x *JsonRpcRequest) GetNumberId() int64 {
	if x, ok := x.GetId().(*JsonRpcRequest_NumberId); ok {
		return x.NumberId
	}
	return 0
}

type isJsonRpcRequest_Id interface {
	isJsonRpcRequest_Id()
}

type JsonRpcRequest_StringId struct {
	StringId string `protobuf:"bytes,4,opt,name=string_id,json=stringId,proto3,oneof"`
}

type JsonRpcRequest_NumberId struct {
	NumberId int64 `protobuf:"varint,5,opt,name=number_id,json=numberId,proto3,oneof"`
}

func (*JsonRpcRequest_StringId) isJsonRpcRequest_Id() {}

func (*JsonRpcRequest_NumberId) isJsonRpcRequest_Id() {}

type JsonRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonrpc string          `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Result  *structpb.Value `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error   *JsonRpcError   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are assignable to Id:
	//
	//	*JsonRpcResponse_StringId
	//	*JsonRpcResponse_NumberId
	Id isJsonRpcResponse_Id `protobuf_oneof:"id"`
}

func (x *JsonRpcResponse) Reset() {
	*x = JsonRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_synapse_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRpcResponse) ProtoMessage() {}

func (x *JsonRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_synapse_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRpcResponse.ProtoReflect.Descriptor instead.
func (*JsonRpcResponse) Descriptor() ([]byte, []int) {
	return file_services_synapse_message_proto_rawDescGZIP(), []int{1}
}

func (x *JsonRpcResponse) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *JsonRpcResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *JsonRpcResponse) GetError() *JsonRpcError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (m *JsonRpcResponse) GetId() isJsonRpcResponse_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *JsonRpcResponse) GetStringId() string {
	if x, ok := x.GetId().(*JsonRpcResponse_StringId); ok {
		return x.StringId
	}
	return ""
}

func (x *JsonRpcResponse) GetNumberId() int64 {
	if x, ok := x.GetId().(*JsonRpcResponse_NumberId); ok {
		return x.NumberId
	}
	return 0
}

type isJsonRpcResponse_Id interface {
	isJsonRpcResponse_Id()
}

type JsonRpcResponse_StringId struct {
	StringId string `protobuf:"bytes,4,opt,name=string_id,json=stringId,proto3,oneof"`
}

type JsonRpcResponse_NumberId struct {
	NumberId int64 `protobuf:"varint,5,opt,name=number_id,json=numberId,proto3,oneof"`
}

func (*JsonRpcResponse_StringId) isJsonRpcResponse_Id() {}

func (*JsonRpcResponse_NumberId) isJsonRpcResponse_Id() {}

type JsonRpcError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *structpb.Value `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *JsonRpcError) Reset() {
	*x = JsonRpcError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_synapse_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonRpcError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRpcError) ProtoMessage() {}

func (x *JsonRpcError) ProtoReflect() protoreflect.Message {
	mi := &file_services_synapse_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRpcError.ProtoReflect.Descriptor instead.
func (*JsonRpcError) Descriptor() ([]byte, []int) {
	return file_services_synapse_message_proto_rawDescGZIP(), []int{2}
}

func (x *JsonRpcError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JsonRpcError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JsonRpcError) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_services_synapse_message_proto protoreflect.FileDescriptor

var file_services_synapse_message_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x79, 0x6e, 0x61, 0x70,
	0x73, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x79, 0x6f, 0x74, 0x74, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x73, 0x79, 0x6e, 0x61, 0x70, 0x73, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x01, 0x0a, 0x0e, 0x4a, 0x73, 0x6f, 0x6e, 0x52,
	0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x73, 0x6f,
	0x6e, 0x72, 0x70, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x73, 0x6f, 0x6e,
	0x72, 0x70, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x09, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x08, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x08, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22,
	0xdb, 0x01, 0x0a, 0x0f, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x73, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x73, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x12, 0x2e, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3a, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79,
	0x6f, 0x74, 0x74, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79,
	0x6e, 0x61, 0x70, 0x73, 0x65, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x70, 0x63, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x09, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0x68, 0x0a,
	0x0c, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x70, 0x63, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x6f, 0x74, 0x74, 0x61, 0x6c, 0x61, 0x62, 0x73, 0x61,
	0x69, 0x2f, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x70, 0x68, 0x69, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x79, 0x6e, 0x61, 0x70, 0x73, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_synapse_message_proto_rawDescOnce sync.Once
	file_services_synapse_message_proto_rawDescData = file_services_synapse_message_proto_rawDesc
)

func file_services_synapse_message_proto_rawDescGZIP() []byte {
	file_services_synapse_message_proto_rawDescOnce.Do(func() {
		file_services_synapse_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_synapse_message_proto_rawDescData)
	})
	return file_services_synapse_message_proto_rawDescData
}

var file_services_synapse_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_synapse_message_proto_goTypes = []interface{}{
	(*JsonRpcRequest)(nil),  // 0: yotta.services.synapse.JsonRpcRequest
	(*JsonRpcResponse)(nil), // 1: yotta.services.synapse.JsonRpcResponse
	(*JsonRpcError)(nil),    // 2: yotta.services.synapse.JsonRpcError
	(*structpb.Value)(nil),  // 3: google.protobuf.Value
}
var file_services_synapse_message_proto_depIdxs = []int32{
	3, // 0: yotta.services.synapse.JsonRpcRequest.params:type_name -> google.protobuf.Value
	3, // 1: yotta.services.synapse.JsonRpcResponse.result:type_name -> google.protobuf.Value
	2, // 2: yotta.services.synapse.JsonRpcResponse.error:type_name -> yotta.services.synapse.JsonRpcError
	3, // 3: yotta.services.synapse.JsonRpcError.data:type_name -> google.protobuf.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_synapse_message_proto_init() }
func file_services_synapse_message_proto_init() {
	if File_services_synapse_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_synapse_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_synapse_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_synapse_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonRpcError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_synapse_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*JsonRpcRequest_StringId)(nil),
		(*JsonRpcRequest_NumberId)(nil),
	}
	file_services_synapse_message_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*JsonRpcResponse_StringId)(nil),
		(*JsonRpcResponse_NumberId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_synapse_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_synapse_message_proto_goTypes,
		DependencyIndexes: file_services_synapse_message_proto_depIdxs,
		MessageInfos:      file_services_synapse_message_proto_msgTypes,
	}.Build()
	File_services_synapse_message_proto = out.File
	file_services_synapse_message_proto_rawDesc = nil
	file_services_synapse_message_proto_goTypes = nil
	file_services_synapse_message_proto_depIdxs = nil
}
