// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: services/synapse/synapse.proto

package synapse

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SynapseServiceClient is the client API for SynapseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SynapseServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	ReportAgentStatus(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*ReportAckResponse, error)
}

type synapseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSynapseServiceClient(cc grpc.ClientConnInterface) SynapseServiceClient {
	return &synapseServiceClient{cc}
}

func (c *synapseServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/yotta.services.synapse.SynapseService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synapseServiceClient) ReportAgentStatus(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*ReportAckResponse, error) {
	out := new(ReportAckResponse)
	err := c.cc.Invoke(ctx, "/yotta.services.synapse.SynapseService/ReportAgentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SynapseServiceServer is the server API for SynapseService service.
// All implementations should embed UnimplementedSynapseServiceServer
// for forward compatibility
type SynapseServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	ReportAgentStatus(context.Context, *AgentStatusRequest) (*ReportAckResponse, error)
}

// UnimplementedSynapseServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSynapseServiceServer struct {
}

func (UnimplementedSynapseServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSynapseServiceServer) ReportAgentStatus(context.Context, *AgentStatusRequest) (*ReportAckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportAgentStatus not implemented")
}

// UnsafeSynapseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SynapseServiceServer will
// result in compilation errors.
type UnsafeSynapseServiceServer interface {
	mustEmbedUnimplementedSynapseServiceServer()
}

func RegisterSynapseServiceServer(s grpc.ServiceRegistrar, srv SynapseServiceServer) {
	s.RegisterService(&SynapseService_ServiceDesc, srv)
}

func _SynapseService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynapseServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yotta.services.synapse.SynapseService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynapseServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SynapseService_ReportAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynapseServiceServer).ReportAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yotta.services.synapse.SynapseService/ReportAgentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynapseServiceServer).ReportAgentStatus(ctx, req.(*AgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SynapseService_ServiceDesc is the grpc.ServiceDesc for SynapseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SynapseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yotta.services.synapse.SynapseService",
	HandlerType: (*SynapseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SynapseService_SayHello_Handler,
		},
		{
			MethodName: "ReportAgentStatus",
			Handler:    _SynapseService_ReportAgentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/synapse/synapse.proto",
}
